"""add ai_request_id to characters

Revision ID: e4fb0a69ff96
Revises: ace30014ad13
Create Date: 2026-09-29 09:30:53.701088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4fb0a69ff96'
down_revision: Union[str, Sequence[str], None] = 'ace30014ad13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('ai_request_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'ai_request_id')
    # ### end Alembic commands ###
